# Муравйов Практична робота 2.2

In [1]:
#task 1
import pandas as pd
data = pd.read_csv('bestsellers with categories.csv', encoding = 'latin1')
df = pd.DataFrame(data)
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [2]:
#task 2
df.head(10)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction

In [3]:
#task 3
print(df.shape)
print("Датасет містить дані про 550 книжок")

(550, 7)
Датасет містить дані про 550 книжок

In [4]:
#task 4
data = pd.read_csv('bestsellers with categories.csv', encoding = 'latin1')
data.columns = ['name', 'author', 'user_rating', 'reviews', 'price', 'year', 'genre']
df = pd.DataFrame(data)
df

,name,author,user_rating,reviews,price,year,genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [5]:
#task 5
missing_values = data.isna().sum()
print(missing_values)
print("\nПропусків немає")

name           0
author         0
user_rating    0
reviews        0
price          0
year           0
genre          0
dtype: int64

Пропусків немає

In [6]:
#task 6
unique_genres = data["genre"].unique()

print('є два унікальних жанри :', unique_genres)

є два унікальних жанри : ['Non Fiction' 'Fiction']

In [7]:
#task 7
max_price = data['price'].max()
min_price = data['price'].min()
mean_price = data['price'].mean()
median_price = data['price'].median()

print(f"Максимальна ціна: |{max_price}| \nМінімальна ціна: |{min_price}| \nСередня ціна: |{mean_price}| \nМедіанна ціна: |{median_price}|")

Максимальна ціна: |105|
Мінімальна ціна: |0|
Середня ціна: |13.1|
Медіанна ціна: |11.0|

In [23]:
#task 8
#Який рейтинг у датасеті найвищий?
max_rating = data['user_rating'].max()
max_rating_book = data[data['user_rating'] == max_rating]

#Скільки книг мають такий рейтинг?

count_max_rating_books = len(max_rating_book)

#Яка книга має найбільше відгуків?

max_reviews = data.loc[data['reviews'].idxmax()]
name_max_reviews_book = max_reviews['name']

#З тих книг, що потрапили до Топ-50 у 2010 році, яка книга найдорожча ?

year_2010 = data[(data['year'] == 2010)]
max_price = year_2010['price'].max()
most_expensive_book = year_2010[year_2010['price'] == max_price]

#Скільки книг жанру Fiction потрапили до Топ-50 у 2012 році

fiction_genre = data[(data["genre"] == "Fiction")]
date = fiction_genre[(fiction_genre['year'] == 2010)]
book_count = len(date)

# Скільки книг з рейтингом 4.9 потрапило до рейтингу у 2010 та 2011 роках (використовуйте | або метод isin)?

high_rating_2010_2011 = data[(data['user_rating'] == 4.9) & (data['year'].isin([2010, 2011]))]
book_counter = len(high_rating_2010_2011)

print(f"Максимальний рейтинг в списку: {max_rating} \n\nКількість книг з найвищим рейтингом: {count_max_rating_books} \n\nКнига з найбільшою кількістю відгуків: {name_max_reviews_book}")
print(f"\nЗ тих книг, що потрапили до Топ-50 у 2010 році, найдорожча книга: \n{most_expensive_book['name'].iloc[0]}")
print(f"\nКількість книг жанру 'Fiction', які потрапили до Топ-50 у 2012 році: {book_count}")
print(f"\nКількість книг з рейтингом 4.9, які потрапили до Топ-50 у 2010 або 2011 роках: {book_counter}")

Максимальний рейтинг в списку: 4.9

Кількість книг з найвищим рейтингом: 52

Книга з найбільшою кількістю відгуків: Where the Crawdads Sing

З тих книг, що потрапили до Топ-50 у 2010 році, найдорожча книга:
Publication Manual of the American Psychological Association, 6th Edition

Кількість книг жанру 'Fiction', які потрапили до Топ-50 у 2012 році: 20

Кількість книг з рейтингом 4.9, які потрапили до Топ-50 у 2010 або 2011 роках: 1

In [24]:
#task 9
filtered_data = data[data['genre'].isin(['Fiction', 'Non Fiction'])]

aggregations = {
    'price': ['min', 'max']
}

result = filtered_data.groupby('genre').agg(aggregations)
print(result)

            price
              min  max
genre
Fiction         0   82
Non Fiction     0  105